version: "3"
services:
  nats:
    image: nats:latest
    command: -m 80
    networks:
      default:
        aliases:
          - nats.agn
    environment:
      HOSTNAME: nats.agn

  redis:
    restart: on-failure
    image: redis:7-alpine
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
    healthcheck:
      test:
        - "CMD"
        - "redis-cli"
        - "--tls"
        - "--cert"
        - "/usr/local/etc/redis/tls/redis.crt"
        - "--key"
        - "/usr/local/etc/redis/tls/redis.key"
        - "--cacert"
        - "/usr/local/etc/redis/tls/ca.crt"
        - "--user"
        - "pgui"
        - "--pass"
        - "''"
        - "ping"
    networks:
      default:
        aliases:
          - redis.agn
    volumes:
      - ./configs/redis:/usr/local/etc/redis
      - redis-tmp:/tmp
    environment:
      HOSTNAME: redis.agn

  redisui:
    depends_on:
      - redis
    restart: on-failure
    image: rediscommander/redis-commander:latest
    healthcheck:
      test:
        - "CMD"
        - "wget"
        - "--no-verbose"
        - "--tries=1"
        - "--spider"
        - "http://localhost"
      interval: 30s
      timeout: 10s
      retries: 5
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - redis-tmp:/tmp/redis
    environment:
      HOSTNAME: redisui.agn

      PORT: 80
      REDIS_SOCKET: /tmp/redis/redis.sock
      REDIS_PASSWORD: "defaultpass"

  mongo:
    image: mongo:latest
    healthcheck:
      test:
        - "CMD"
        - "mongo"
        - "--norc"
        - "--quiet"
        - "--eval"
        - "'db.getMongo()'"
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      default:
        aliases:
          - mongo.agn
    volumes:
      - ./.persist/mongo:/data/db
    environment:
      HOSTNAME: mongo.agn

  mongoui:
    depends_on:
      - mongo
    image: mongo-express:latest
    healthcheck:
      test:
        - "CMD"
        - "wget"
        - "--no-verbose"
        - "--tries=1"
        - "--spider"
        - "http://localhost"
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      HOSTNAME: mongoui.agn

      ME_CONFIG_MONGODB_SERVER: mongo.agn
      ME_CONFIG_OPTIONS_EDITORTHEME: darcula
      VCAP_APP_PORT: 80

  postgres:
    restart: on-failure
    image: postgres:latest
    healthcheck:
      test:
        - "CMD-SHELL"
        - "pg_isready -U postgres -p 5432"
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      default:
        aliases:
          - postgres.agn
    volumes:
      - ./entrypoints/postgres:/docker-entrypoint-initdb.d
      - ./configs/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./.persist/postgres:/var/lib/postgresql/data
      # - ./configs/postgres/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - postgres-run:/var/run/postgresql
    environment:
      HOSTNAME: postgres.agn

      POSTGRES_PASSWORD: pass
      POSTGRES_MULTIPLE_DATABASES: 'agn_configs,agnostic : agn_cars,agnostic'

  postgresui:
    depends_on:
      - postgres
    restart: on-failure
    image: dpage/pgadmin4:latest
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "cp /tmp/pgpassfile.org /tmp/pgpassfile && chmod 600 /tmp/pgpassfile && /entrypoint.sh"
    healthcheck:
      test:
        - "CMD"
        - "wget"
        - "--no-verbose"
        - "--tries=1"
        - "--spider"
        - "http://localhost"
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      default:
        aliases:
          - postgresui.agn
    volumes:
      - ./configs/pgadmin/servers.json:/pgadmin4/servers.json
      - ./configs/pgadmin/pgpassfile:/tmp/pgpassfile.org
    environment:
      HOSTNAME: postgresui.agn

      PGADMIN_DEFAULT_EMAIL: dba@tech.agn
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_CONFIG_LOGIN_BANNER: '"Use `dba@tech.agn` for email and `secret` for password"'
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      PGADMIN_DISABLE_POSTFIX: "True"

  jaeger:
    restart: on-failure
    image: jaegertracing/all-in-one:latest
    healthcheck:
      test:
        - "CMD"
        - "wget"
        - "--no-verbose"
        - "--tries=1"
        - "--spider"
        - "http://localhost:14269"
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      default:
        aliases:
          - jaeger.agn
    environment:
      HOSTNAME: jaeger.agn

      QUERY_HTTP_SERVER_HOST_PORT: :80

      COLLECTOR_ZIPKIN_HOST_PORT: :9411
      SPAN_STORAGE_TYPE: badger

volumes:
  postgres-run:
  redis-tmp:
